import { useState, type ReactNode } from 'react'
import { posts } from './content/posts'
import { Switchboard } from './components/Switchboard'
import jonnyPortrait from './assets/jonny-phaser.png'
import './App.css'

function Panel({ title, children, id, className = '' }: { title: string; children: ReactNode; id?: string; className?: string }) {
  return <section id={id} className={`panel ${className}`}><div className="titlebar"><span>{title}</span><span aria-hidden="true">─ □</span></div>{children}</section>
}
function Sunset() {
  return <svg className="sunset" viewBox="0 0 1100 230" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><defs><linearGradient id="sky" x2="0" y2="1"><stop stopColor="#251637"/><stop offset="1" stopColor="#8c305d"/></linearGradient><pattern id="bands" width="8" height="14" patternUnits="userSpaceOnUse"><rect width="8" height="10" fill="#ffad87"/></pattern></defs><rect width="1100" height="230" fill="url(#sky)"/><circle cx="820" cy="116" r="104" fill="url(#bands)"/><path fill="#191329" d="M0 185H620V161H648V137H662V161H697V177H722V148H745V170H774V156H796V183H837V167H873V137H898V159H923V183H970V166H1000V185H1100V230H0Z"/><g stroke="#b44985" opacity=".6"><path d="M0 202H1100M0 218H1100M550 190L150 230M550 190L350 230M550 190L750 230M550 190L950 230"/></g><g fill="#120f21"><path d="M981 225Q963 115 994 45L1000 48Q981 133 998 225Z M994 48Q947 13 917 48Q957 31 989 54Q927 41 913 83Q953 57 990 58Q967 69 971 105Q985 77 998 56Q1028 86 1056 87Q1041 50 1003 50Q1048 37 1075 57Q1054 15 998 44Q1013 12 1038 7Q1002 3 994 48Z"/><path transform="translate(385 42) scale(.7)" d="M981 225Q963 115 994 45L1000 48Q981 133 998 225Z M994 48Q947 13 917 48Q957 31 989 54Q927 41 913 83Q953 57 990 58Q967 69 971 105Q985 77 998 56Q1028 86 1056 87Q1041 50 1003 50Q1048 37 1075 57Q1054 15 998 44Q1013 12 1038 7Q1002 3 994 48Z"/></g></svg>
}
const services = [['01', 'Surveillance', 'Looking. But professionally.', '◉'], ['02', 'Missing Things', 'Somewhere is a place. I start there.', '⌕'], ['03', 'Background Checks', 'Everybody has a background. Suspicious.', '▤']]
export default function App() {
  const [phoneOpen, setPhoneOpen] = useState(false)
  const [openPost, setOpenPost] = useState<string | null>(null)
  const [service, setService] = useState('')
  const call = () => setPhoneOpen(true)
  return <><a className="skip" href="#main">Skip to content</a><div className="shell" id="home">
    <div className="system-strip"><span><i className="led"/> AGENCY ONLINE · 2026</span><span>THREAT LEVEL: HANDSOME</span><span>EST. IN HIS OWN MIND</span></div>
    <header className="masthead"><Sunset/><div className="brand"><span className="eyebrow">PRIVATE INVESTIGATION. PUBLIC CONFIDENCE.</span><h1>RADICAL<span>-PI</span></h1><p>The truth doesn't stand a chance.</p></div><span className="header-stamp">100%<br/>PHASER<br/><small>APPROVED</small></span></header>
    <nav className="main-nav" aria-label="Main navigation"><a href="#home">Home</a><a href="#services">Services</a><a href="#about">About Jonny</a><a href="#field-notes">Field Notes</a><button onClick={call}>☎ Call the Office</button></nav>
    <div className="ticker"><strong>LATEST DISPATCH</strong><span>The internet is now under observation. Carry on normally.</span><span className="ticker-end">END TRANSMISSION ▪</span></div>
    <div className="portal"><main id="main">
      <Panel title="01 / WELCOME TO THE OPERATION" className="intro"><div className="intro-inner"><div><span className="eyebrow pink">YOUR PROBLEM. MY SUNGLASSES.</span><h2>Somebody knows<br/>something.<br/><em>Probably me.</em></h2><p>Jonathan “Jonny Phaser” McPhaser.<br/>Private investigator. Extremely available.<br/>Quiet discretion. Loud jacket energy.</p><button className="primary" onClick={call}>☎ CALL THE OFFICE <span>↗</span></button><small>No problem too vague.</small></div><div className="portrait"><span className="portrait-label">PERSONNEL FILE / 001</span><img src={jonnyPortrait} width="1024" height="1536" alt="Jonny Phaser in sunglasses and a neon tropical shirt, holding a cassette recorder outside his office at sunset."/><span className="portrait-caption">JONNY PHASER</span><small>Discretion has a face.</small></div></div><div className="intro-bottom"><span>DISCRETION: ALLEGED</span><span>CONFIDENCE: EXCESSIVE</span><span>SHADES: ON</span></div></Panel>
      <Panel title="02 / PROFESSIONAL-ISH SERVICES" id="services"><div className="service-grid">{services.map(([number, title, description, icon]) => <article className="service" key={number}><div className="service-icon" aria-hidden="true">{icon}<small>{number}</small></div><h3>{title}</h3><p>{description}</p><button onClick={() => { setService(title); call() }}>Make an inquiry ↗</button></article>)}</div></Panel>
      <Panel title="03 / THE MAN BEHIND THE BLINDS" id="about"><div className="about-content"><div><span className="eyebrow">OWNER / LEAD EVERYTHING</span><h2>Jonny Phaser.</h2><p>A discharged police officer with private-investigator ambitions, spectacular self-belief, and a flexible relationship with good judgment.</p><p>It is 2026. Nobody tell his wardrobe.</p></div><div className="credentials"><span>SELF-CERTIFIED <b>EXPERT</b></span><span>COMPUTER SKILLS <b>ON / OFF</b></span><span>INSTINCT RATING <b>11 / 10</b></span></div></div></Panel>
      <Panel title="04 / FIELD NOTES" id="field-notes"><div className="notes-heading"><h2>From the desk of Phaser.</h2><span className="tag">DRAFT FILES</span></div>{posts.map(post => <article className="post" key={post.id}><div className="post-meta"><time dateTime={post.date}>{new Date(`${post.date}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: '2-digit', year: 'numeric' })}</time><span>DRAFT · CONTENT PENDING</span></div><h3>{post.title}</h3><p>{post.excerpt}</p><button className="text-button" aria-expanded={openPost === post.id} aria-controls={`entry-${post.id}`} onClick={() => setOpenPost(openPost === post.id ? null : post.id)}>{openPost === post.id ? 'Close Entry −' : 'Read Entry +'}</button><div id={`entry-${post.id}`} hidden={openPost !== post.id} className="entry-body">{post.image && <img src={post.image} alt=""/>}<p>{post.body}</p><small>Draft entry awaiting future content.</small></div></article>)}</Panel>
    </main><aside aria-label="Agency bulletin board">
      <Panel title="AGENCY STATUS"><div className="widget"><div className="online"><i className="led"/> OPERATIONAL*</div><dl><div><dt>Office</dt><dd>Probably open</dd></div><div><dt>Technology</dt><dd>Under suspicion</dd></div><div><dt>Current year</dt><dd>2026. Allegedly.</dd></div></dl><small>*By our own standards.</small></div></Panel>
      <div className="confidence"><span className="eyebrow">CASE CONFIDENCE</span><strong>110<span>%</span></strong><div className="meter"/><p>Before hearing the details.</p><small>SELF-REPORTED. NOT A SUCCESS RATE.</small></div>
      <Panel title="DIRECT LINE"><div className="widget direct"><span className="phone-icon" aria-hidden="true">☎</span><h3>Got a feeling?</h3><p>I've built an entire business on one.</p><button onClick={call}>Call the Office ↗</button><small>Answering machine pending.</small></div></Panel>
      <div className="notice-board"><span>OFFICIAL OFFICE NOTICE</span><h3>NO FAX.<br/>TOO TRACEABLE.</h3><p>Also, the machine is confusing.</p></div>
      <Panel title="VISITOR SURVEILLANCE"><div className="widget visitors"><span className="counter">000086</span><p>You have been counted.</p><small>Simulated counter · local display</small></div></Panel>
      <div className="supplier"><span>A GRÅZON WEB PRODUCTION</span><strong>BIG VISION.<br/>SMALL WEBSITE.</strong><small>Imported confidence. Domestic problems.</small></div>
    </aside></div>
    <footer><div><strong>RADICAL-PI</strong><span>© 2026 · Jonny Phaser's corner of the internet.</span><a href="#home">Back to top ↑</a></div><p>Website by GRÅZON. Results may vary. Confidence will not.</p><small>Radical-PI is a fictional creative project.</small></footer>
  </div>{phoneOpen && <Switchboard inquiry={service} onClose={() => { setPhoneOpen(false); setService('') }}/>}</>
}

